title: Eder VALDERRAMA # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>Je suis un développeur passionné spécialisé en Python, Selenium, Data Science et Finance avec +6 ans d'expérience en analyse, stratégie et vente dans les services financiers. Titulaire d'une licence en économie et d'une maîtrise en science des données de l'<a href='https://www5.usp.br/'>Université de São Paulo</a>. Anciennement chez <a href='https://www.credit-suisse.com/br/pt/quem-somos.html'>Credit Suisse</a>, <a href="https://www.safra.com.br/">Banco Safra</a> et <a href="https://www.pinheironeto.com.br/">Pinheiro Neto Advogados</a>.
  <br><a href="https://www.linkedin.com/in/eder-valderrama-5563aaa5/?locale=fr_FR">LinkedIn Profile</a>
  <br>Email: <a href='eder.valderrama@usp.br'>eder.valderrama@usp.br</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
