title: Eder VALDERRAMA # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>Je suis un développeur passionné spécialisé en Python, Selenium, Data Science et Finance. J'ai acquis une solide expérience dans ces domaines grâce à plusieurs projets et collaborations stimulantes. Je suis constamment à la recherche de nouvelles opportunités pour mettre mes compétences à profit et résoudre des problèmes informatiques complexes.
  <br><a href="https://www.linkedin.com/in/eder-valderrama-5563aaa5/?locale=fr_FR">LinkedIn Profile</a>
  <br>Email: <a href='eder.valderrama@usp.br'>eder.valderrama@usp.br</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
